export const CardsJson = [
  {
    id:1,
    name: "Leanne Graham",
    email: "Sincere@april.biz",
    phone: "1-770-736-8031 x56442",
    website: "http://hildegard.org",
    isLiked: false,
  },
  {
    id:2,
    name: "Ervin Howell",
    email: "Shanna@melissa.tv",
    phone: "010-692-6593 x09125",
    website: "http://anastasia.net",
    isLiked: false,
  },
  {
    id:3,
    name: "Clementine Bauch",
    email: "Nathan@yesenia.net",
    phone: "1-463-123-4447",
    website: "http://ramiro.info",
    isLiked: false,
  },
  {
    id:4,
    name: "Patricia Lebsack",
    email: "Julianne.OConner@kory.org",
    phone: "493-170-9623 x156",
    website: "http://kale.biz",
    isLiked: false,
  },
  {
    id:5,
    name: "Chelsey Dietrich",
    email: "Lucio_Hettinger@annie.ca",
    phone: "(254)954-1289",
    website: "http://demarco.info",
    isLiked: false,
  },
  {
    id:6,
    name: "Mrs. Dennis Schulist",
    email: "Karley_Dach@jasper.info",
    phone: "1-477-935-8478 x6430",
    website: "http://ola.org",
    isLiked: false,
  },
  {
    id:7,
    name: "Kurtis Weissnat",
    email: "Telly.Hoeger@billy.biz",
    phone: "210.067.6132",
    website: "http://elvis.io",
    isLiked: false,
  },
  {
    id:8,
    name: "Nicholas Runolfsdottir V",
    email: "Sherwood@rosamond.me",
    phone: "586.493.6943 x140",
    website: "http://jacynthe.com",
    isLiked: false,
  },
  {
    id:9,
    name: "Glenna Reichert",
    email: "Chaim_McDermott@dana.io",
    phone: "(775)976-6794 x41206",
    website: "http://conrad.com",
    isLiked: false,
  },
  {
    id:10,
    name: "Clementina DuBuque",
    email: "Rey.Padberg@karina.biz",
    phone: "024-648-3804",
    website: "http://ambrose.net",
    isLiked: false,
  },
];
